baseURL = "https://llighter.github.io/hugo_blog"
languageCode = "ko-kr"
title = "llighter's blog"
theme = "temple"
copyright = "(c) 2018 - 2018"
publishDir = "docs"

[params]
  # Enables syntax highlighting
  highlight = true 

  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for what's included in original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim"]

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"
# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "PARK YUNHA"
  github = "llighter"
  email = "hadbsgk@gmail.com"
  gaid = "Your Google Analytics ID"
  twitter = "llighter90"
  medium = "llighter"

[permalinks]
  posts = "/:year/:month/:slug/"